Cms\ContentManagerBundle\Entity\Content:
    type: entity
    table: null
    repositoryClass: Cms\ContentManagerBundle\Entity\ContentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contentsId:
            type: integer
        contentName:
            type: string
            length: '50'
        contentType:
            type: integer
        templateId:
            type: integer
        homePage:
            type: integer
        active:
            type: integer
        pageTitle:
            type: string
            length: '70'
        created:
            type: datetime
        modified:
            type: time
        modifiedBy:
            type: integer
        url:
            type: string
            length: 255
    lifecycleCallbacks: {  }
