oni_content_manager_homepage:
    path:     /content
    defaults: { _controller: content_controller:indexAction }

oni_content_manager_edit_page:
    path:     /content/add
    defaults: { _controller: content_controller:addAction }

oni_content_manager_add_page:
    path:     /content/add
    defaults: { _controller: content_controller:addAction }
