parameters:
    #content_manager_entity_languages: Oni\ContentManagerBundle\Entity\Languages

services:
    oni_content_entity:
        class: Oni\ContentManagerBundle\Entity\Content
    oni_content_form:
        class:     Oni\ContentManagerBundle\Form\ContentForm
        arguments: ["@oni_content_entity"]
    oni_content_controller:
        class:     Oni\ContentManagerBundle\Controller\IndexController
        arguments: ["@templating","@oni_content_form"]
#        calls:
#              - [setContentForm, ["@content_form"]]